# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Frame, Tk, Canvas, Entry, Text, Button, PhotoImage

class login_frame(Frame):
    
    def __init__(self, window):
        Frame.__init__(self, window)

        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path("./assets")

        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)

        canvas = Canvas(
            self,
            bg = "#A54848",
            height = 590,
            width = 1267,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            1267.0,
            590.0,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            228.0,
            107.0,
            1039.0,
            294.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            233.0,
            112.0,
            1034.0,
            289.0,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            515.0,
            198.0,
            776.0,
            288.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            776.0,
            197.0,
            1033.0,
            287.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            776.0,
            113.0,
            1033.0,
            203.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            515.0,
            113.0,
            776.0,
            203.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            520.0,
            203.0,
            771.0,
            283.0,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            520.0,
            118.0,
            771.0,
            198.0,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            776.0,
            203.0,
            1027.0,
            283.0,
            fill="#000000",
            outline="")

        entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        entry_bg_1 = canvas.create_image(
            901.5,
            158.0,
            image=entry_image_1
        )
        entry_1 = Entry(
            self,
            bd=0,
            bg="#000000",
            highlightthickness=0
        )
        entry_1.place(
            x=776.0,
            y=118.0,
            width=251.0,
            height=78.0
        )

        canvas.create_text(
            281.0,
            166.0,
            anchor="nw",
            text="User ID",
            fill="#FFFFFF",
            font=("Roboto", 30 * -1)
        )

        canvas.create_text(
            537.0,
            139.0,
            anchor="nw",
            text="Entry",
            fill="#FFFFFF",
            font=("Roboto", 30 * -1)
        )

        canvas.create_text(
            537.0,
            222.0,
            anchor="nw",
            text="Valid",
            fill="#FFFFFF",
            font=("Roboto", 30 * -1)
        )

        canvas.create_text(
            808.0,
            219.0,
            anchor="nw",
            text="temp123",
            fill="#FFFFFF",
            font=("Roboto", 30 * -1)
        )

        button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        button_1 = Button(
            self,
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat"
        )
        button_1.image = button_image_1
        button_1.place(
            x=537.0,
            y=387.0,
            width=162.0,
            height=95.0
        )

        self.canvas = canvas
