
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Frame, StringVar, Tk, Canvas, Entry, Text, Button, PhotoImage


class login_gui(Frame):

    def __init__(self, window):
        Frame.__init__(self, window)

        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path("./assets")

        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)

        canvas = Canvas(
            self,
            bg = "#000000",
            height = 860,
            width = 1883,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            1883.0,
            860.0,
            fill="#FFFFFF",
            outline="")


        canvas.create_rectangle(
            4.0,
            3.0,
            1878.0,
            855.0,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            535.0,
            247.0,
            1346.0,
            428.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            540.0,
            252.0,
            1341.0,
            422.0,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            822.0,
            338.0,
            1083.0,
            428.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            1083.0,
            337.0,
            1340.0,
            427.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            1083.0,
            253.0,
            1340.0,
            343.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            822.0,
            253.0,
            1083.0,
            343.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            827.0,
            343.0,
            1078.0,
            423.0,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            827.0,
            258.0,
            1078.0,
            338.0,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            1083.0,
            343.0,
            1334.0,
            423.0,
            fill="#000000",
            outline="")

        entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        entry_bg_1 = canvas.create_image(
            1208.5,
            298.0,
            image=entry_image_1,
        )

        self.entry_text = StringVar(self)
        entry_1 = Entry(
            self,
            bd=0,
            bg="#000000",
            highlightthickness=0,
            font="-family {Roboto} -size -30 -weight normal -underline 0 -overstrike 0",
            fg="#FFFFFF",
            textvariable=self.entry_text,
            show="*"
        )
        entry_1.place(
            x=1083.0,
            y=258.0,
            width=251.0,
            height=78.0
        )

        canvas.create_text(
            588.0,
            306.0,
            anchor="nw",
            text="User ID",
            fill="#FFFFFF",
            font=("Roboto", 30 * -1)
        )

        canvas.create_text(
            844.0,
            279.0,
            anchor="nw",
            text="Entry",
            fill="#FFFFFF",
            font=("Roboto", 30 * -1)
        )

        canvas.create_text(
            844.0,
            362.0,
            anchor="nw",
            text="Valid",
            fill="#FFFFFF",
            font=("Roboto", 30 * -1)
        )

        self.valid_text = StringVar(canvas, "")
        self.valid_text_id = canvas.create_text(
            1090.0,
            359.0,
            anchor="nw",
            text=self.valid_text.get(),
            fill="#FFFFFF",
            font=("Roboto", 30 * -1)
        )

        button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        button_1 = Button(
            self,
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            relief="flat"
        )
        button_1.image = button_image_1
        button_1.place(
            x=844.0,
            y=527.0,
            width=162.0,
            height=95.0
        )

        self.canvas = canvas
        self.button_1 = button_1
