# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Frame, Tk, Canvas, Entry, Text, Button, PhotoImage

class test_frame(Frame):

    def __init__(self, window):
        Frame.__init__(self, window)

        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path("./assets")

        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)

        canvas = Canvas(
            self,
            bg = "#A54848",
            height = 590,
            width = 1267,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            0.0,
            1267.0,
            590.0,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            303.0,
            154.0,
            964.0,
            435.0,
            fill="#0037FD",
            outline="")

        canvas.create_text(
            578.0,
            272.0,
            anchor="nw",
            text="Hello",
            fill="#FFFFFF",
            font=("Roboto", 48 * -1)
        )
        
        self.canvas = canvas
