# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import StringVar, Tk, Canvas, Entry, Text, Button, PhotoImage, Frame, Radiobutton
import datetime

class emu_gui(Frame):

    def __init__(self, window):
        Frame.__init__(self, window)

        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path("./assets")

        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)

        time_text = StringVar(window, "")

        canvas = Canvas(
            self,
            bg = "#000000",
            height = 1080,
            width = 1920,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        button_1 = Radiobutton(
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            relief="flat",
            compound="center",
            font="-family {Roboto} -size -30 -weight normal -underline 0 -overstrike 0",
            variable=9999,
            value=1,
            indicatoron=False
        )
        button_1.place(
            x=18.0,
            y=93.0,
            width=162.0,
            height=95.0,
        )

        button_image_2 = PhotoImage(
            file=relative_to_assets("button_2.png"))
        button_2 = Radiobutton(
            window,
            image=button_image_2,
            borderwidth=0,
            highlightthickness=0,
            # command=lambda: print("button_2 clicked"),
            relief="flat",
            compound="center",
            font="-family {Roboto} -size -30 -weight normal -underline 0 -overstrike 0",
            variable=9999,
            value=2,
            indicatoron=False
        )
        button_2.place(
            x=190.0,
            y=93.0,
            width=162.0,
            height=95.0
        )

        button_image_3 = PhotoImage(
            file=relative_to_assets("button_3.png"))
        button_3 = Radiobutton(
            image=button_image_3,
            borderwidth=0,
            highlightthickness=0,
            # command=lambda: print("button_3 clicked"),
            relief="flat",
            compound="center",
            font="-family {Roboto} -size -30 -weight normal -underline 0 -overstrike 0",
            variable=9999,
            value=3,
            indicatoron=False
        )
        button_3.place(
            x=362.0,
            y=93.0,
            width=162.0,
            height=95.0
        )

        button_image_4 = PhotoImage(
            file=relative_to_assets("button_4.png"))
        button_4 = Radiobutton(
            image=button_image_4,
            borderwidth=0,
            highlightthickness=0,
            # command=lambda: print("button_4 clicked"),
            relief="flat",
            compound="center",
            font="-family {Roboto} -size -30 -weight normal -underline 0 -overstrike 0",
            variable=9999,
            value=4,
            indicatoron=False
        )
        button_4.place(
            x=534.0,
            y=93.0,
            width=162.0,
            height=95.0
        )

        button_image_5 = PhotoImage(
            file=relative_to_assets("button_5.png"))
        button_5 = Radiobutton(
            image=button_image_5,
            borderwidth=0,
            highlightthickness=0,
            # command=lambda: print("button_5 clicked"),
            relief="flat",
            compound="center",
            font="-family {Roboto} -size -30 -weight normal -underline 0 -overstrike 0",
            variable=9999,
            value=5,
            indicatoron=False
        )
        button_5.place(
            x=706.0,
            y=93.0,
            width=162.0,
            height=95.0
        )

        button_image_6 = PhotoImage(
            file=relative_to_assets("button_6.png"))
        button_6 = Radiobutton(
            image=button_image_6,
            borderwidth=0,
            highlightthickness=0,
            # command=lambda: print("button_6 clicked"),
            relief="flat",
            compound="center",
            font="-family {Roboto} -size -30 -weight normal -underline 0 -overstrike 0",
            variable=9999,
            value=6,
            indicatoron=False
        )
        button_6.place(
            x=878.0,
            y=93.0,
            width=162.0,
            height=95.0
        )

        button_image_7 = PhotoImage(
            file=relative_to_assets("button_7.png"))
        button_7 = Radiobutton(
            image=button_image_7,
            borderwidth=0,
            highlightthickness=0,
            # command=lambda: print("button_7 clicked"),
            relief="flat",
            compound="center",
            font="-family {Roboto} -size -30 -weight normal -underline 0 -overstrike 0",
            variable=9999,
            value=7,
            indicatoron=False
        )
        button_7.place(
            x=1050.0,
            y=93.0,
            width=162.0,
            height=95.0
        )

        button_image_8 = PhotoImage(
            file=relative_to_assets("button_8.png"))
        button_8 = Radiobutton(
            image=button_image_8,
            borderwidth=0,
            highlightthickness=0,
            # command=lambda: print("button_8 clicked"),
            relief="flat",
            compound="center",
            font="-family {Roboto} -size -30 -weight normal -underline 0 -overstrike 0",
            variable=9999,
            value=8,
            indicatoron=False
        )
        button_8.place(
            x=1222.0,
            y=93.0,
            width=162.0,
            height=95.0
        )

        button_image_9 = PhotoImage(
            file=relative_to_assets("button_9.png"))
        button_9 = Radiobutton(
            image=button_image_9,
            borderwidth=0,
            highlightthickness=0,
            # command=lambda: print("button_9 clicked"),
            relief="flat",
            compound="center",
            font="-family {Roboto} -size -30 -weight normal -underline 0 -overstrike 0",
            variable=9999,
            value=9,
            indicatoron=False
        )
        button_9.place(
            x=1394.0,
            y=93.0,
            width=162.0,
            height=95.0
        )

        button_image_10 = PhotoImage(
            file=relative_to_assets("button_10.png"))
        button_10 = Radiobutton(
            image=button_image_10,
            borderwidth=0,
            highlightthickness=0,
            # command=lambda: print("button_10 clicked"),
            relief="flat",
            compound="center",
            font="-family {Roboto} -size -30 -weight normal -underline 0 -overstrike 0",
            variable=9999,
            value=10,
            indicatoron=False
        )
        button_10.place(
            x=1566.0,
            y=93.0,
            width=162.0,
            height=95.0
        )

        button_image_11 = PhotoImage(
            file=relative_to_assets("button_11.png"))
        button_11 = Radiobutton(
            image=button_image_11,
            borderwidth=0,
            highlightthickness=0,
            # command=self.exit_gui,
            relief="flat",
            compound="center",
            font="-family {Roboto} -size -30 -weight normal -underline 0 -overstrike 0",
            variable=9999,
            value=11,
            indicatoron=False,
        )
        button_11.place(
            x=1738.0,
            y=93.0,
            width=162.0,
            height=95.0
        )

        canvas.create_rectangle(
            18.0,
            204.0,
            1901.0,
            1064.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            22.0,
            208.0,
            1896.0,
            1060.0,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            1669.0,
            16.0,
            1905.0,
            81.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            1673.0,
            20.0,
            1901.0,
            77.0,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            1426.0,
            16.0,
            1673.0,
            81.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            1430.0,
            20.0,
            1669.0,
            77.0,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            490.0,
            16.0,
            1430.0,
            81.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            495.0,
            20.0,
            1426.0,
            77.0,
            fill="#000000",
            outline="")

        canvas.create_rectangle(
            18.0,
            16.0,
            495.0,
            81.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            22.0,
            20.0,
            490.0,
            77.0,
            fill="#000000",
            outline="")

        time_text_id = canvas.create_text(
            1729.0,
            31.0,
            anchor="nw",
            text=time_text,
            fill="#FFFFFF",
            font=("Roboto", 30 * -1)
        )

        canvas.create_text(
            1472.0,
            31.0,
            anchor="nw",
            text=str(datetime.datetime.today().strftime('%d/%m/%Y')),
            fill="#FFFFFF",
            font=("Roboto", 30 * -1)
        )

        canvas.create_text(
            173.0,
            31.0,
            anchor="nw",
            text="Train: 69145",
            fill="#FFFFFF",
            font=("Roboto", 30 * -1)
        )

        self.frame_id_text = StringVar(canvas, "Login User ID")
        self.frame_id = canvas.create_text(
            871.0,
            31.0,
            anchor="nw",
            text="Login User ID",
            fill="#FFFFFF",
            font=("Roboto", 30 * -1)
        )

        def cur_clock():
            time = str(datetime.datetime.now().strftime("%H:%M:%S"))
            canvas.itemconfig(time_text_id, text=time)
            window.after(1000,cur_clock)

        window.after(0,cur_clock)

        button_1.image = button_image_1
        button_2.image = button_image_2
        button_3.image = button_image_3
        button_4.image = button_image_4
        button_5.image = button_image_5
        button_6.image = button_image_6
        button_7.image = button_image_7
        button_8.image = button_image_8
        button_9.image = button_image_9
        button_10.image = button_image_10
        button_11.image = button_image_11

        self.window = window
        self.canvas = canvas
        self.button_1 = button_1
        self.button_2 = button_2
        self.button_3 = button_3
        self.button_4 = button_4
        self.button_5 = button_5
        self.button_6 = button_6
        self.button_7 = button_7
        self.button_8 = button_8
        self.button_9 = button_9
        self.button_10 = button_10
        self.button_11 = button_11

        self.button_list = [
            self.button_1,
            self.button_2,
            self.button_3,
            self.button_4,
            self.button_5,
            self.button_6,
            self.button_7,
            self.button_8,
            self.button_9,
            self.button_10,
            self.button_11
        ]
