
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *

class statusFrame(Frame):

    def __init__(self, window):
        Frame.__init__(self, window)

        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path("./assets")

        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)

        canvas = Canvas(
            self,
            bg = "#000000",
            height = 590,
            width = 1267,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            237.99999999999977,
            103.0,
            1028.9999999999998,
            486.0,
            fill="#FD471F",
            outline="")

        canvas.create_rectangle(
            477.9999999999998,
            235.0,
            789.9999999999998,
            354.0,
            fill="#C4C4C4",
            outline="")

        canvas.create_text(
            584.9999999999998,
            272.0,
            anchor="nw",
            text="Test",
            fill="#000000",
            font=("Roboto", 48 * -1)
        )

        self.canvas = canvas
